import { Pool } from 'pg'
import { query } from './db'
import { PlanName } from './stripe'

// Called after Stripe payment succeeds
// Creates the school's isolated DB and sets everything up
export async function provisionSchool(schoolId: string) {
  const school = await getSchool(schoolId)
  if (!school) throw new Error('School not found')

  try {
    // 1. Create the school's database
    await createSchoolDatabase(school.db_name)

    // 2. Run migrations on the new DB
    await runMigrations(school.db_connection_string)

    // 3. Create R2 storage folder (just a convention, R2 is flat)
    await createStorageFolder(school.subdomain)

    // 4. Mark school as active
    await query(
      'UPDATE schools SET status = $1, provisioned_at = NOW() WHERE id = $2',
      ['active', schoolId]
    )

    console.log(`School ${school.subdomain} provisioned successfully`)
    return { success: true }

  } catch (error) {
    console.error(`Provisioning failed for school ${schoolId}:`, error)
    await query(
      'UPDATE schools SET status = $1 WHERE id = $2',
      ['provision_failed', schoolId]
    )
    throw error
  }
}

async function createSchoolDatabase(dbName: string) {
  // Connect to Render Postgres instance as superuser to create a new DB
  const adminPool = new Pool({
    connectionString: process.env.DATABASE_URL,
    ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
  })

  const client = await adminPool.connect()
  try {
    // Can't use parameterised queries for CREATE DATABASE
    // dbName is generated by us (safe, not user input)
    await client.query(`CREATE DATABASE ${dbName}`)
    console.log(`Database ${dbName} created`)
  } finally {
    client.release()
    await adminPool.end()
  }
}

async function runMigrations(connectionString: string) {
  // Connect to the newly created school DB and run all migrations
  const schoolPool = new Pool({
    connectionString,
    ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
  })

  const client = await schoolPool.connect()
  try {
    // Run your Django migrations via a REST call to your Django backend
    // OR run raw SQL schema here if you extract it from Django
    // For now this is a placeholder — will connect to Django provisioning endpoint
    const response = await fetch(`${process.env.DJANGO_BACKEND_URL}/api/provision/migrate/`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Provision-Key': process.env.PROVISION_SECRET_KEY!,
      },
      body: JSON.stringify({ connection_string: connectionString }),
    })

    if (!response.ok) throw new Error('Migration failed')
    console.log('Migrations completed')
  } finally {
    client.release()
    await schoolPool.end()
  }
}

async function createStorageFolder(subdomain: string) {
  // R2 is a flat bucket — "folders" are just key prefixes
  // We create a placeholder file to initialise the folder
  // Full R2 integration to be added in Phase 3
  console.log(`Storage folder ready: ${subdomain}/`)
}

async function getSchool(schoolId: string) {
  const result = await query('SELECT * FROM schools WHERE id = $1', [schoolId])
  return result.rows[0] || null
}

// Generate a safe DB name from school subdomain
export function generateDbName(subdomain: string): string {
  const safe = subdomain.toLowerCase().replace(/[^a-z0-9]/g, '_')
  return `school_${safe}`
}

// Generate the DB connection string for a school
export function generateConnectionString(dbName: string): string {
  const base = process.env.DATABASE_URL!
  const url = new URL(base)
  url.pathname = `/${dbName}`
  return url.toString()
}
